---

- name: Install packages needed to compile coturn server
  apt:
    name:
      - gcc
      - make
      - autoconf
      - libevent-dev
      - libsqlite3-dev
    state: present

- name: Create coturn install dir
  file:
    path: "{{ turn_path }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755

- name: Download and extract coturn
  unarchive:
    src: "{{ turn_tarball_url }}"
    dest: "{{ turn_path }}"
    owner: root
    group: root
    copy: no
    creates: "{{ turn_path }}/{{ turn_archive }}"
  register: turn_download

- name: Compile and install coturn
  command: "{{ item }}"
  args:
    chdir: "{{ turn_path }}/{{ turn_archive }}"
  with_items:
    - ./configure
    - /usr/bin/make
    - /usr/bin/make install
  when: turn_download.changed

- name: Install turnserver config
  template:
    src: etc/turnserver.conf.j2
    dest: /etc/turnserver.conf
  notify:
    - restart turn server

- name: Install systemd service
  template:
    src: etc/systemd/system/turnserver.service.j2
    dest: /etc/systemd/system/turnserver.service
    mode: 0644
  notify:
    - reload systemctl daemon
    - restart turn server
