---

- name: Create riot.im install dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ riot_path }}/.well-known"

- name: Download and extract riot.im
  unarchive:
    src: "{{ riot_im_tarball_url }}"
    dest: "{{ riot_path }}"
    owner: root
    group: root
    copy: no
    creates: "{{ riot_path }}/{{ riot_im_archive }}"
  when: not ansible_check_mode

- name: riot.im configuration
  template:
    src: riot_config.json.j2
    dest: "{{ riot_path }}/{{ riot_im_archive }}/config.{{ riot_hostname }}.json"
    owner: root
    group: root
    mode: 0664

- name: Install nginx conf for riot.im
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'etc/nginx/sites-available/riot.j2', dest: '/etc/nginx/sites-available/{{ riot_hostname }}' }
  notify:
    - restart nginx

- name: Enable the riot.im vhost (symlink)
  file:
    src: /etc/nginx/sites-available/{{ riot_hostname }}
    dest: /etc/nginx/sites-enabled/{{ riot_hostname }}
    state: link
  notify:
    - restart nginx
  when: not ansible_check_mode
