- name: reload systemctl daemon
  systemd: daemon_reload=yes
  tags: synapse, turnserver, mxisd, riot

- name: restart turn server
  service: name=turnserver state=restarted enabled=yes
  tags: turnserver

- name: restart ma1sd
  service: name=ma1sd state=restarted enabled=yes
  tags: ma1sd

- name: restart mxisd
  service: name=mxisd state=restarted enabled=yes
  tags: mxisd

- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  tags: riot

- name: restart synapse
  service: name=synapse state=restarted enabled=yes
  tags: synapse

- name: restart postgresql
  service: name=postgresql state=restarted enabled=yes
<<<<<<< HEAD
  tags: postgres
=======
  tags: postgres
>>>>>>> upstream/master
